name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  all-php-versions:
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1", "8.2", "8.3"]

    uses: ./.github/workflows/main-php-matrix.yml
    with:
      php: ${{ matrix.php }}
    secrets: inherit

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0


  phptats:
    name: PHPStat
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: composer install --ignore-platform-req=*

      - name: Run PHPStat
        run: php run.php
